# Generated by Django 4.2.28 on 2026-03-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_public_page_visible_page_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
    ]
